spring.application.name=operator-service
spring.config.import=optional:configserver:http://localhost:8888
app.jwt.secret=omnicharge-secret-key-must-be-at-least-32-chars-long
eureka.client.webclient.enabled=false