spring.application.name=config-server
spring.cloud.config.server.git.uri=https://github.com/mass17052005/omnicharge-config
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.clone-on-start=true
server.port=8888
management.endpoints.web.exposure.include=*